CREATE DATABASE SOCIALPETS;

USE SOCIALPETS;

CREATE TABLE PERDIDOS(
CODIGO INT UNSIGNED AUTO_INCREMENT,
NOME VARCHAR(80) NOT NULL,
RACA VARCHAR(80) NOT NULL,
DONO VARCHAR(80) NOT NULL,
EMAIL_DONO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
PATH VARCHAR(100) NOT NULL,
NOMEIMAGEM VARCHAR(100) NOT NULL,
SEXO CHAR(1) NOT NULL,
DATA_PERDA DATE NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
PRIMARY KEY(CODIGO)
)ENGINE=INNODB;



CREATE TABLE ABANDONADOS (
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
RACA VARCHAR(80) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
PATH VARCHAR(100) NOT NULL,
NOMEIMAGEM VARCHAR(100) NOT NULL,
SEXO CHAR(1) NOT NULL,
DATA_ENCONTRADO DATE NOT NULL,
DESCRICAO VARCHAR(100) NOT NULL,
PRIMARY KEY(CODIGO)
)ENGINE=INNODB;



CREATE TABLE USUARIOS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
EMAIL VARCHAR(150) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
PRIMARY KEY(CODIGO)
)ENGINE=INNODB;


SELECT * FROM PERDIDOS;
SELECT * FROM ABANDONADOS;
SELECT * FROM USUARIOS;



INSERT INTO USUARIOS VALUES(1,"alice@gmail.com",'12345');
select *from usuarios where email = "alice@gmail.com" and senha="12345";